package com.datanymize.export;

import com.datanymize.database.connection.IDatabaseConnection;
import com.datanymize.database.model.DatabaseSchema;
import com.datanymize.export.model.ExportFormat;
import com.datanymize.export.model.ExportResult;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Exporter for Docker image format with database setup.
 * Validates: Requirements 7.1, 7.5
 */
public class DockerImageExporter implements IExporter {
    private ProgressListener progressListener;
    private volatile boolean cancelled = false;
    private volatile boolean running = false;
    private String databaseType; // postgresql, mysql, mongodb

    public DockerImageExporter(String databaseType) {
        this.databaseType = databaseType;
    }

    @Override
    public ExportResult export(
        IDatabaseConnection connection,
        DatabaseSchema schema,
        ExportFormat format,
        String outputPath
    ) throws Exception {
        ExportResult result = new ExportResult();
        result.setExportId(generateExportId());
        result.setFormat(format);
        result.setOutputPath(outputPath);

        running = true;
        cancelled = false;

        try {
            // Create output directory
            File outputDir = new File(outputPath);
            if (!outputDir.exists()) {
                outputDir.mkdirs();
            }

            // Generate SQL dump first
            String dumpPath = outputPath + File.separator + "data.sql";
            IExporter sqlExporter = createSQLExporter();
            sqlExporter.export(connection, schema, getExportFormat(), dumpPath);

            if (cancelled) {
                throw new InterruptedException("Export cancelled");
            }

            // Generate Dockerfile
            String dockerfilePath = outputPath + File.separator + "Dockerfile";
            generateDockerfile(dockerfilePath, schema);

            if (cancelled) {
                throw new InterruptedException("Export cancelled");
            }

            // Generate docker-compose.yml
            String dockerComposePath = outputPath + File.separator + "docker-compose.yml";
            generateDockerCompose(dockerComposePath, schema);

            if (cancelled) {
                throw new InterruptedException("Export cancelled");
            }

            // Generate entrypoint script
            String entrypointPath = outputPath + File.separator + "entrypoint.sh";
            generateEntrypoint(entrypointPath, schema);

            result.setRowsExported(0); // Docker export doesn't count rows directly
            result.setTablesExported(schema.getTables().size());
            result.markComplete();

            if (progressListener != null) {
                progressListener.onComplete(result);
            }

        } catch (Exception e) {
            result.markFailed(e.getMessage());
            if (progressListener != null) {
                progressListener.onError("Docker export failed: " + e.getMessage(), e);
            }
            throw e;
        } finally {
            running = false;
        }

        return result;
    }

    @Override
    public void setProgressListener(ProgressListener listener) {
        this.progressListener = listener;
    }

    @Override
    public void cancel() {
        this.cancelled = true;
    }

    @Override
    public boolean isRunning() {
        return running;
    }

    private void generateDockerfile(String dockerfilePath, DatabaseSchema schema) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(dockerfilePath))) {
            writer.write("# Dockerfile generated by Datanymize\n");
            writer.write("# Timestamp: " + LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME) + "\n\n");

            if ("postgresql".equalsIgnoreCase(databaseType)) {
                writer.write("FROM postgres:15-alpine\n\n");
                writer.write("ENV POSTGRES_DB=" + schema.getDatabaseName() + "\n");
                writer.write("ENV POSTGRES_USER=datanymize\n");
                writer.write("ENV POSTGRES_PASSWORD=datanymize\n\n");
                writer.write("COPY data.sql /docker-entrypoint-initdb.d/\n");
                writer.write("COPY entrypoint.sh /\n");
                writer.write("RUN chmod +x /entrypoint.sh\n\n");
                writer.write("EXPOSE 5432\n");
                writer.write("CMD [\"postgres\"]\n");
            } else if ("mysql".equalsIgnoreCase(databaseType)) {
                writer.write("FROM mysql:8.0\n\n");
                writer.write("ENV MYSQL_DATABASE=" + schema.getDatabaseName() + "\n");
                writer.write("ENV MYSQL_USER=datanymize\n");
                writer.write("ENV MYSQL_PASSWORD=datanymize\n");
                writer.write("ENV MYSQL_ROOT_PASSWORD=root\n\n");
                writer.write("COPY data.sql /docker-entrypoint-initdb.d/\n");
                writer.write("COPY entrypoint.sh /\n");
                writer.write("RUN chmod +x /entrypoint.sh\n\n");
                writer.write("EXPOSE 3306\n");
                writer.write("CMD [\"mysqld\"]\n");
            } else if ("mongodb".equalsIgnoreCase(databaseType)) {
                writer.write("FROM mongo:6.0\n\n");
                writer.write("ENV MONGO_INITDB_DATABASE=" + schema.getDatabaseName() + "\n\n");
                writer.write("COPY data.sql /docker-entrypoint-initdb.d/\n");
                writer.write("COPY entrypoint.sh /\n");
                writer.write("RUN chmod +x /entrypoint.sh\n\n");
                writer.write("EXPOSE 27017\n");
                writer.write("CMD [\"mongod\"]\n");
            }
        }
    }

    private void generateDockerCompose(String dockerComposePath, DatabaseSchema schema) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(dockerComposePath))) {
            writer.write("version: '3.8'\n\n");
            writer.write("services:\n");
            writer.write("  database:\n");
            writer.write("    build: .\n");
            writer.write("    container_name: datanymize-" + schema.getDatabaseName() + "\n");

            if ("postgresql".equalsIgnoreCase(databaseType)) {
                writer.write("    environment:\n");
                writer.write("      POSTGRES_DB: " + schema.getDatabaseName() + "\n");
                writer.write("      POSTGRES_USER: datanymize\n");
                writer.write("      POSTGRES_PASSWORD: datanymize\n");
                writer.write("    ports:\n");
                writer.write("      - \"5432:5432\"\n");
            } else if ("mysql".equalsIgnoreCase(databaseType)) {
                writer.write("    environment:\n");
                writer.write("      MYSQL_DATABASE: " + schema.getDatabaseName() + "\n");
                writer.write("      MYSQL_USER: datanymize\n");
                writer.write("      MYSQL_PASSWORD: datanymize\n");
                writer.write("      MYSQL_ROOT_PASSWORD: root\n");
                writer.write("    ports:\n");
                writer.write("      - \"3306:3306\"\n");
            } else if ("mongodb".equalsIgnoreCase(databaseType)) {
                writer.write("    environment:\n");
                writer.write("      MONGO_INITDB_DATABASE: " + schema.getDatabaseName() + "\n");
                writer.write("    ports:\n");
                writer.write("      - \"27017:27017\"\n");
            }

            writer.write("    volumes:\n");
            writer.write("      - db_data:/data\n\n");
            writer.write("volumes:\n");
            writer.write("  db_data:\n");
        }
    }

    private void generateEntrypoint(String entrypointPath, DatabaseSchema schema) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(entrypointPath))) {
            writer.write("#!/bin/bash\n");
            writer.write("# Entrypoint script generated by Datanymize\n");
            writer.write("# Timestamp: " + LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME) + "\n\n");

            if ("postgresql".equalsIgnoreCase(databaseType)) {
                writer.write("set -e\n");
                writer.write("echo 'PostgreSQL database initialization starting...'\n");
                writer.write("exec \"$@\"\n");
            } else if ("mysql".equalsIgnoreCase(databaseType)) {
                writer.write("set -e\n");
                writer.write("echo 'MySQL database initialization starting...'\n");
                writer.write("exec \"$@\"\n");
            } else if ("mongodb".equalsIgnoreCase(databaseType)) {
                writer.write("set -e\n");
                writer.write("echo 'MongoDB database initialization starting...'\n");
                writer.write("exec \"$@\"\n");
            }
        }
    }

    private IExporter createSQLExporter() {
        if ("postgresql".equalsIgnoreCase(databaseType)) {
            return new PostgreSQLDumpExporter();
        } else if ("mysql".equalsIgnoreCase(databaseType)) {
            return new MySQLDumpExporter();
        } else if ("mongodb".equalsIgnoreCase(databaseType)) {
            return new MongoDBDumpExporter();
        }
        throw new IllegalArgumentException("Unsupported database type: " + databaseType);
    }

    private ExportFormat getExportFormat() {
        if ("postgresql".equalsIgnoreCase(databaseType)) {
            return ExportFormat.POSTGRESQL_DUMP;
        } else if ("mysql".equalsIgnoreCase(databaseType)) {
            return ExportFormat.MYSQL_DUMP;
        } else if ("mongodb".equalsIgnoreCase(databaseType)) {
            return ExportFormat.MONGODB_DUMP;
        }
        throw new IllegalArgumentException("Unsupported database type: " + databaseType);
    }

    private String generateExportId() {
        return "export_" + System.currentTimeMillis();
    }
}
