package com.datanymize.export;

import com.datanymize.database.connection.IDatabaseConnection;
import com.datanymize.database.model.Column;
import com.datanymize.database.model.DatabaseSchema;
import com.datanymize.database.model.ForeignKey;
import com.datanymize.database.model.Row;
import com.datanymize.database.model.Table;
import com.datanymize.export.model.ExportFormat;
import com.datanymize.export.model.ExportResult;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Exporter for MySQL SQL dump format (mysqldump compatible).
 * Validates: Requirements 7.1, 7.3
 */
public class MySQLDumpExporter implements IExporter {
    private ProgressListener progressListener;
    private volatile boolean cancelled = false;
    private volatile boolean running = false;

    @Override
    public ExportResult export(
        IDatabaseConnection connection,
        DatabaseSchema schema,
        ExportFormat format,
        String outputPath
    ) throws Exception {
        if (format != ExportFormat.MYSQL_DUMP) {
            throw new IllegalArgumentException("This exporter only supports MYSQL_DUMP format");
        }

        ExportResult result = new ExportResult();
        result.setExportId(generateExportId());
        result.setFormat(format);
        result.setOutputPath(outputPath);

        running = true;
        cancelled = false;

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputPath))) {
            // Write header
            writeHeader(writer, schema);

            // Write CREATE TABLE statements
            long totalRows = 0;
            for (Table table : schema.getTables()) {
                if (cancelled) {
                    throw new InterruptedException("Export cancelled");
                }
                writeCreateTableStatement(writer, table, schema);
                totalRows += table.getRowCount();
            }

            // Write INSERT statements
            long rowsProcessed = 0;
            for (Table table : schema.getTables()) {
                if (cancelled) {
                    throw new InterruptedException("Export cancelled");
                }

                List<Row> rows = readTableData(connection, table);
                for (Row row : rows) {
                    if (cancelled) {
                        throw new InterruptedException("Export cancelled");
                    }
                    writeInsertStatement(writer, row);
                    rowsProcessed++;

                    // Update progress
                    if (progressListener != null && rowsProcessed % 100 == 0) {
                        int percentComplete = (int) ((rowsProcessed * 100) / Math.max(totalRows, 1));
                        progressListener.onProgress(table.getName(), rowsProcessed, totalRows, percentComplete);
                    }
                }

                result.getTableStats().put(table.getName(), (long) rows.size());
            }

            // Write footer
            writeFooter(writer);

            result.setRowsExported(rowsProcessed);
            result.setTablesExported(schema.getTables().size());
            result.markComplete();

            if (progressListener != null) {
                progressListener.onComplete(result);
            }

        } catch (Exception e) {
            result.markFailed(e.getMessage());
            if (progressListener != null) {
                progressListener.onError("Export failed: " + e.getMessage(), e);
            }
            throw e;
        } finally {
            running = false;
        }

        return result;
    }

    @Override
    public void setProgressListener(ProgressListener listener) {
        this.progressListener = listener;
    }

    @Override
    public void cancel() {
        this.cancelled = true;
    }

    @Override
    public boolean isRunning() {
        return running;
    }

    private void writeHeader(BufferedWriter writer, DatabaseSchema schema) throws IOException {
        writer.write("-- MySQL database dump\n");
        writer.write("-- Generated by Datanymize\n");
        writer.write("-- Timestamp: " + LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME) + "\n");
        writer.write("-- Database: " + schema.getDatabaseName() + "\n\n");
        writer.write("/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n");
        writer.write("/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n");
        writer.write("/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n");
        writer.write("/*!40101 SET NAMES utf8mb4 */;\n");
        writer.write("/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;\n");
        writer.write("/*!40103 SET TIME_ZONE='+00:00' */;\n");
        writer.write("/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;\n");
        writer.write("/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;\n");
        writer.write("/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n\n");
    }

    private void writeCreateTableStatement(BufferedWriter writer, Table table, DatabaseSchema schema)
        throws IOException {
        writer.write("DROP TABLE IF EXISTS `" + table.getName() + "`;\n");
        writer.write("CREATE TABLE `" + table.getName() + "` (\n");

        List<String> columnDefs = new ArrayList<>();
        for (Column col : table.getColumns()) {
            StringBuilder colDef = new StringBuilder();
            colDef.append("  `").append(col.getName()).append("` ").append(col.getDataType());

            if (!col.isNullable()) {
                colDef.append(" NOT NULL");
            }

            if (col.getDefaultValue() != null) {
                colDef.append(" DEFAULT ").append(col.getDefaultValue());
            }

            columnDefs.add(colDef.toString());
        }

        // Add primary key constraint
        if (!table.getPrimaryKeys().isEmpty()) {
            StringBuilder pkDef = new StringBuilder("  PRIMARY KEY (");
            for (int i = 0; i < table.getPrimaryKeys().size(); i++) {
                if (i > 0) pkDef.append(", ");
                pkDef.append("`").append(table.getPrimaryKeys().get(i)).append("`");
            }
            pkDef.append(")");
            columnDefs.add(pkDef.toString());
        }

        // Add unique constraints
        if (!table.getUniqueKeys().isEmpty()) {
            for (String uniqueKey : table.getUniqueKeys()) {
                columnDefs.add("  UNIQUE KEY `" + uniqueKey + "_unique` (`" + uniqueKey + "`)");
            }
        }

        // Add foreign key constraints
        for (ForeignKey fk : schema.getForeignKeys()) {
            if (fk.getSourceTable().equals(table.getName())) {
                StringBuilder fkDef = new StringBuilder("  CONSTRAINT `");
                fkDef.append(fk.getName()).append("` FOREIGN KEY (`");
                fkDef.append(fk.getSourceColumn()).append("`) REFERENCES `");
                fkDef.append(fk.getTargetTable()).append("` (`");
                fkDef.append(fk.getTargetColumn()).append("`)");
                columnDefs.add(fkDef.toString());
            }
        }

        writer.write(String.join(",\n", columnDefs));
        writer.write("\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n\n");
    }

    private void writeInsertStatement(BufferedWriter writer, Row row) throws IOException {
        StringBuilder insert = new StringBuilder("INSERT INTO `");
        insert.append(row.getTableName()).append("` (");

        List<String> columns = new ArrayList<>(row.getValues().keySet());
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) insert.append(", ");
            insert.append("`").append(columns.get(i)).append("`");
        }

        insert.append(") VALUES (");
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) insert.append(", ");
            Object value = row.getValues().get(columns.get(i));
            insert.append(escapeSQLValue(value));
        }

        insert.append(");\n");
        writer.write(insert.toString());
    }

    private void writeFooter(BufferedWriter writer) throws IOException {
        writer.write("\n/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;\n");
        writer.write("/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;\n");
        writer.write("/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;\n");
        writer.write("/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;\n");
        writer.write("/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n");
        writer.write("/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n");
        writer.write("/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n");
        writer.write("-- MySQL database dump complete\n");
    }

    private String escapeSQLValue(Object value) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof String) {
            return "'" + ((String) value).replace("\\", "\\\\").replace("'", "\\'") + "'";
        }
        if (value instanceof Boolean) {
            return ((Boolean) value) ? "1" : "0";
        }
        return value.toString();
    }

    private List<Row> readTableData(IDatabaseConnection connection, Table table) throws SQLException {
        List<Row> rows = new ArrayList<>();
        String query = "SELECT * FROM `" + table.getName() + "`";
        ResultSet rs = connection.executeQuery(query);

        while (rs.next()) {
            Row row = new Row();
            row.setTableName(table.getName());

            for (Column col : table.getColumns()) {
                Object value = rs.getObject(col.getName());
                row.getValues().put(col.getName(), value);
            }

            rows.add(row);
        }

        return rows;
    }

    private String generateExportId() {
        return "export_" + System.currentTimeMillis();
    }
}
