package com.datanymize.export;

import com.datanymize.database.connection.IDatabaseConnection;
import com.datanymize.database.model.Column;
import com.datanymize.database.model.DatabaseSchema;
import com.datanymize.database.model.ForeignKey;
import com.datanymize.database.model.Row;
import com.datanymize.database.model.Table;
import com.datanymize.export.model.ExportFormat;
import com.datanymize.export.model.ExportResult;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Exporter for PostgreSQL SQL dump format (pg_dump compatible).
 * Validates: Requirements 7.1, 7.2
 */
public class PostgreSQLDumpExporter implements IExporter {
    private ProgressListener progressListener;
    private volatile boolean cancelled = false;
    private volatile boolean running = false;

    @Override
    public ExportResult export(
        IDatabaseConnection connection,
        DatabaseSchema schema,
        ExportFormat format,
        String outputPath
    ) throws Exception {
        if (format != ExportFormat.POSTGRESQL_DUMP) {
            throw new IllegalArgumentException("This exporter only supports POSTGRESQL_DUMP format");
        }

        ExportResult result = new ExportResult();
        result.setExportId(generateExportId());
        result.setFormat(format);
        result.setOutputPath(outputPath);

        running = true;
        cancelled = false;

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputPath))) {
            // Write header
            writeHeader(writer, schema);

            // Write CREATE TABLE statements
            long totalRows = 0;
            for (Table table : schema.getTables()) {
                if (cancelled) {
                    throw new InterruptedException("Export cancelled");
                }
                writeCreateTableStatement(writer, table, schema);
                totalRows += table.getRowCount();
            }

            // Write INSERT statements
            long rowsProcessed = 0;
            for (Table table : schema.getTables()) {
                if (cancelled) {
                    throw new InterruptedException("Export cancelled");
                }

                List<Row> rows = readTableData(connection, table);
                for (Row row : rows) {
                    if (cancelled) {
                        throw new InterruptedException("Export cancelled");
                    }
                    writeInsertStatement(writer, row);
                    rowsProcessed++;

                    // Update progress
                    if (progressListener != null && rowsProcessed % 100 == 0) {
                        int percentComplete = (int) ((rowsProcessed * 100) / Math.max(totalRows, 1));
                        progressListener.onProgress(table.getName(), rowsProcessed, totalRows, percentComplete);
                    }
                }

                result.getTableStats().put(table.getName(), (long) rows.size());
            }

            // Write footer
            writeFooter(writer);

            result.setRowsExported(rowsProcessed);
            result.setTablesExported(schema.getTables().size());
            result.markComplete();

            if (progressListener != null) {
                progressListener.onComplete(result);
            }

        } catch (Exception e) {
            result.markFailed(e.getMessage());
            if (progressListener != null) {
                progressListener.onError("Export failed: " + e.getMessage(), e);
            }
            throw e;
        } finally {
            running = false;
        }

        return result;
    }

    @Override
    public void setProgressListener(ProgressListener listener) {
        this.progressListener = listener;
    }

    @Override
    public void cancel() {
        this.cancelled = true;
    }

    @Override
    public boolean isRunning() {
        return running;
    }

    private void writeHeader(BufferedWriter writer, DatabaseSchema schema) throws IOException {
        writer.write("-- PostgreSQL database dump\n");
        writer.write("-- Generated by Datanymize\n");
        writer.write("-- Timestamp: " + LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME) + "\n");
        writer.write("-- Database: " + schema.getDatabaseName() + "\n\n");
        writer.write("SET statement_timeout = 0;\n");
        writer.write("SET lock_timeout = 0;\n");
        writer.write("SET idle_in_transaction_session_timeout = 0;\n");
        writer.write("SET client_encoding = 'UTF8';\n");
        writer.write("SET standard_conforming_strings = on;\n");
        writer.write("SET check_function_bodies = false;\n");
        writer.write("SET client_min_messages = warning;\n");
        writer.write("SET row_security = off;\n\n");
    }

    private void writeCreateTableStatement(BufferedWriter writer, Table table, DatabaseSchema schema)
        throws IOException {
        writer.write("CREATE TABLE " + escapeIdentifier(table.getName()) + " (\n");

        List<String> columnDefs = new ArrayList<>();
        for (Column col : table.getColumns()) {
            StringBuilder colDef = new StringBuilder();
            colDef.append("    ").append(escapeIdentifier(col.getName())).append(" ").append(col.getDataType());

            if (!col.isNullable()) {
                colDef.append(" NOT NULL");
            }

            if (col.getDefaultValue() != null) {
                colDef.append(" DEFAULT ").append(col.getDefaultValue());
            }

            columnDefs.add(colDef.toString());
        }

        // Add primary key constraint
        if (!table.getPrimaryKeys().isEmpty()) {
            StringBuilder pkDef = new StringBuilder("    PRIMARY KEY (");
            for (int i = 0; i < table.getPrimaryKeys().size(); i++) {
                if (i > 0) pkDef.append(", ");
                pkDef.append(escapeIdentifier(table.getPrimaryKeys().get(i)));
            }
            pkDef.append(")");
            columnDefs.add(pkDef.toString());
        }

        // Add unique constraints
        if (!table.getUniqueKeys().isEmpty()) {
            for (String uniqueKey : table.getUniqueKeys()) {
                columnDefs.add("    UNIQUE (" + escapeIdentifier(uniqueKey) + ")");
            }
        }

        // Add foreign key constraints
        for (ForeignKey fk : schema.getForeignKeys()) {
            if (fk.getSourceTable().equals(table.getName())) {
                StringBuilder fkDef = new StringBuilder("    FOREIGN KEY (");
                fkDef.append(escapeIdentifier(fk.getSourceColumn())).append(") REFERENCES ");
                fkDef.append(escapeIdentifier(fk.getTargetTable())).append(" (");
                fkDef.append(escapeIdentifier(fk.getTargetColumn())).append(")");
                columnDefs.add(fkDef.toString());
            }
        }

        writer.write(String.join(",\n", columnDefs));
        writer.write("\n);\n\n");
    }

    private void writeInsertStatement(BufferedWriter writer, Row row) throws IOException {
        StringBuilder insert = new StringBuilder("INSERT INTO ");
        insert.append(escapeIdentifier(row.getTableName())).append(" (");

        List<String> columns = new ArrayList<>(row.getValues().keySet());
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) insert.append(", ");
            insert.append(escapeIdentifier(columns.get(i)));
        }

        insert.append(") VALUES (");
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) insert.append(", ");
            Object value = row.getValues().get(columns.get(i));
            insert.append(escapeSQLValue(value));
        }

        insert.append(");\n");
        writer.write(insert.toString());
    }

    private void writeFooter(BufferedWriter writer) throws IOException {
        writer.write("\n-- PostgreSQL database dump complete\n");
    }

    private String escapeIdentifier(String identifier) {
        return "\"" + identifier.replace("\"", "\"\"") + "\"";
    }

    private String escapeSQLValue(Object value) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof String) {
            return "'" + ((String) value).replace("'", "''") + "'";
        }
        if (value instanceof Boolean) {
            return ((Boolean) value) ? "true" : "false";
        }
        return value.toString();
    }

    private List<Row> readTableData(IDatabaseConnection connection, Table table) throws SQLException {
        List<Row> rows = new ArrayList<>();
        String query = "SELECT * FROM " + escapeIdentifier(table.getName());
        ResultSet rs = connection.executeQuery(query);

        while (rs.next()) {
            Row row = new Row();
            row.setTableName(table.getName());

            for (Column col : table.getColumns()) {
                Object value = rs.getObject(col.getName());
                row.getValues().put(col.getName(), value);
            }

            rows.add(row);
        }

        return rows;
    }

    private String generateExportId() {
        return "export_" + System.currentTimeMillis();
    }
}
